### ISSUE TITLE
Create `dangerous` version of p-button

### ISSUE THREAD

**Issue by stackoverfloweth** [PrefectHQ/prefect-design#265]
<img width="101" alt="image" src="https://user-images.githubusercontent.com/6098901/176779203-e4512fea-e0e8-4554-9775-205003297c10.png">

```css
.organization-leave__leave-button { @apply
  bg-red-500
  focus:ring-red-600
  hover:!bg-red-700
}
```
